name1 = input("Input a Name\n")
object1 = input("Input an Object\n")
name2 = input("Input a Name\n")
colour1 = input("Input a Colour\n")
object2 = input("Input another Object\n")
adjective1 = input("Input an Adjective\n")
number1 = input("Input a Number\n")
number2 = input("Input another Number\n")
time1 = input("Input a Time of Day\n")
adjective2 = input("Input another Adjective\n")

print("\t",name1,"walks through the dark woods where they see a spooky",object1,". that spooky",object1,"was actually just their friend",name2,". the duo continued thought the woods and found a",colour1, object2,". This",object2,"was at least a foot long, and very",adjective1,". The duo rounded a tree and found",number1,"more.\n\t This was all really spooky so the duo decided to leave. They were both",number2,"years old and it was past their bedtime (it was",time1,"). as the two began to walk away, they heard a",adjective2,"noise. As the two began to panic at the sound,",name2,"started seizing up.\n\t",name2,"fell to the ground and died on the spot, leaving",name1,"alone as they always were.",name1,", seeing how their fun spooky time with",name2,"was over, decided it was time to wake up.\n\n\t",name1,"rose up from their bed, staring at the white box they were in, and felt a faint whiff of burt toast")
